tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/versions"
tap "cloudfoundry/tap"
tap "git-duet/tap"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "universal-ctags/universal-ctags"

brew "aria2"
brew "automake"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "bash-git-prompt"
brew "bison"
brew "chruby"
brew "cscope"
brew "cloudfoundry/tap/bosh-cli"
brew "coreutils"
brew "direnv"
brew "docker"
brew "fasd"
brew "gdbm"
brew "git"
brew "git-duet/tap/git-duet"
brew "gnupg"
brew "go"
brew "htop"
brew "jq"
brew "lastpass-cli"
brew "libffi"
brew "libyaml"
# brew "mysql", restart_service: true
brew "neovim"
brew "openssl"
brew "pinentry-mac"
brew "postgresql@10", restart_service: true
brew "python3"
brew "readline"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "ruby-install"
brew "shellcheck"
brew "tig"
brew "tmux"
brew "tree"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "watch"
brew "pcre"   #secretly required for wget
brew "wget"
brew "elixir"

cask "caskroom/fonts/font-firacode-nerd-font"
cask "caskroom/versions/firefox-nightly"
cask "caskroom/versions/iterm2-nightly"
cask "vlc"
cask "docker"
cask "flycut"
cask "google-cloud-sdk"
cask "google-chrome"
cask "spectacle"
cask "virtualbox"
cask "zoomus"
